version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: bookshop_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshop
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  springboot:
    build: .
    container_name: bookshop_app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  mariadb_data:
